version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::095470518884:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-6wYdo5m2UiaH"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::095470518884:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-WipM6iATPPSj"
cloudformation_execution_role = "arn:aws:iam::095470518884:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-rRPynJBJEinV"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-m6gt6wocayyy"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::095470518884:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-nMg8RVI48W1s"
cloudformation_execution_role = "arn:aws:iam::095470518884:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-eXepeHznV72r"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-bd7uovelq1jd"
image_repository = ""
region = "us-east-1"
